#!/usr/bin/env Rscript

###################################################################
####calculate accuracy metrics for PRScs in disease trait      ####
####Ying Wang (yiwang@broadinstitute.org) in July-2021         ####
###################################################################

########load packages needed########
library(data.table)
library(pROC) #for calculating AUC & its 95% CIs
library(boot) #for calculating CIs for NKr2 & h2l_NKr2
library(optparse) #for parsing arguments

#########parsing argument options########
option_list <- list(
  make_option(c("-f", "--files"), type = "character", default = NULL, help = "Full path and file names listing  *.profile or *.sscore files generated by plink, separated by comma"),
  make_option(c("--pop"), type = "character", default = NULL, help = "Target ancestry"),
  make_option(c("--pheno"), type = "character", default = NULL, help = "Phenotype name in the phenotype file"),
  make_option(c("--prop"), type = "character", default = NULL, help = "Proportion of total samples selected to tune the parameter or get the weight"),
  make_option(c("--reps"), type = "character", default = NULL, help = "The number of replications repeated of data splitting"),
  make_option(c("--K"), type = "character", default = NULL, help = "Disease prevalence"),
  make_option(c("--covs"), type = "character", default = NULL, help = "Covariates included in the prediction model, separated by comma"),
  make_option(c("--pc_numbers"), type = "character", default = "PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10", help = "PCs included in the prediction model, separated by comma"),
  make_option(c("--phenofile"), type = "character", default = NULL, help = "Full path and file name to phenotype files (including FID, IID, phenotypes etc.)"),
  make_option(c("--popfile"), type = "character", default = NULL, help = "Full path and file name to the file listing IDs for unrelated individuals in the target population (in the format of FID, IID as the first two columns)"),
   make_option(c("--covfile"), type = "character", default = NULL, help = "Full path and file name to the file including covariates (with headers including FID, IID and covariates)"),
  make_option(c("--pcfile"), type = "character", default = NULL, help = "Full path and file name to the file including PCs (e.g., headers including FID, IID, PC1, PC2, PC3...)"),
  make_option(c("--cohort_name"), type = "character", default = NULL, help = "Your specific Biobanks name"),
  make_option(c("--ldref"), type = "character", default = NULL, help = "The LD reference panel used (e.g., 1KG or UKB)"),
  make_option(c("--out_weights"), type = "character", default = NULL, help = "Full path and file name for the output file of the prs accuracy metrics using cross-validation"),
  make_option(c("--wt"), type = "character", default = "NKr2", help = "Statistic used as the weight, e.g., NKr2 or h2l_NKr2"),
  make_option(c("--out_test_metrics"), type = "character", default = NULL, help = "Full path and file name for the output file of accuracy metrics in the test cohort")
)

opt = parse_args(OptionParser(option_list=option_list))


files <- opt$files
pop <- opt$pop
pheno <- opt$pheno
prop <- as.numeric(opt$prop)
reps <- as.numeric(opt$reps)
K <- opt$K
covs <- opt$covs
pc_numbers <- opt$pc_numbers
phenofile <- opt$phenofile
popfile <- opt$popfile
covfile <- opt$covfile
pcfile <- opt$pcfile
cohort <- opt$cohort_name
ldref <- opt$ldref
out_weights <- opt$out_weights
wt <- opt$wt
out_test_metrics <- opt$out_test_metrics

#########################Functions used#########################
cal_NKr2_auc <- function(dat){
  ##base model with covariates only: Age + Sex + 10PCs
  glm0 <- glm(as.formula(paste("PHENO ~ ", exp0)), data = dat, family = binomial(logit)) 
  
  # logistic full model with PRS
  glm1 <- glm(as.formula(paste("PHENO ~ ", exp1)), data = dat, family = binomial(logit)) 
  
  # Calculate Cox & Snell R2 using log Likelihoods 
  LL1 <-  logLik(glm1)
  LL0 <-  logLik(glm0)
  CSr2 <-  round(1 - exp((2 / N) * (LL0[1] - LL1[1])), 6)
  
  # Calculate Nagelkerke's R2
  NKr2 <- round(CSr2 / (1 - exp((2 / N) * LL0[1])), 6)  
  # Test whether NKr2 is significantly different from 0
  devdiff <- round(glm0$deviance - glm1$deviance, 1) #Difference in deviance attributable to PRS
  df <- glm0$df.residual - glm1$df.residual #1 degree of freedom for single variable PRS
  NKr2_pval <- pchisq(devdiff, df, lower.tail = F)
  
  ## Calculate AUC using full model (PRS+covariates)
  auc1 <- round(auc(dat$PHENO, glm1$linear.predictors), 3)
  
  # Calculate AUC using only PRS
  glm3 <- glm(PHENO ~ ZSCORE, data = dat, family = binomial(logit))
  auc2 <- round(auc(dat$PHENO, glm3$linear.predictors), 3)
  
  auc1_2.5 <- round(ci.auc(dat$PHENO, glm1$linear.predictors)[1], 3)
  auc1_97.5 <- round(ci.auc(dat$PHENO, glm1$linear.predictors)[3], 3)
  
  auc2_2.5 <- round(ci.auc(dat$PHENO, glm3$linear.predictors)[1], 3)
  auc2_97.5 <- round(ci.auc(dat$PHENO, glm3$linear.predictors)[3], 3)
  
  return(data.frame(NKr2, NKr2_pval, 
                    auc1, auc1_2.5, auc1_97.5, 
                    auc2, auc2_2.5, auc2_97.5))
}  


#################calculate proportion of variance explained on the liability scale#################
# Ref: Lee et al., Genet Epidemiol. 2012 Apr;36(3):214-24.
h2l_R2s <- function(k, r2, p) {
  # k baseline disease risk
  # r2 from a linear regression model of genomic profile risk score (R2v/NKr2)
  # p proportion of cases
  x <- qnorm(1 - k)
  z <- dnorm(x)
  i <- z / k
  C <- k * (1 - k) * k * (1 - k) / (z^2 * p * (1 - p))
  theta <- i * ((p - k) / (1 - k)) * (i * ((p - k) / (1 - k)) - x)
  e <- 1 - p^(2 * p) * (1 - p)^(2 * (1 - p))
  h2l_NKr2 <- C * e * r2 / (1 + C * e * theta * r2)
  h2l_NKr2 <- round(h2l_NKr2, 6)
  return(h2l_NKr2)
} 


# Calculate 95% CI for Nagelkerke's R2 & h2l_NKr2
boot_function <- function(data, indices){
  d <- data[indices,]
  NKr2 <- cal_NKr2_auc(d)$NKr2
  h2l_NKr2 <- h2l_R2s(K, NKr2, P)
  return(c(NKr2, h2l_NKr2))
}


################Read input files################
if(phenofile != "NULL"){
  phen <- fread(phenofile) 
} else{
  print("No phenotype files for input")
}

if(popfile != "NULL"){
  ids <- fread(popfile, header = F) 
} else{
  ids <- phen[,c("FID", "IID")]
  names(ids) <- c("V1", "V2")
}

if(length(covs) > 0 & covfile != "NULL" & covs != "NULL"){
  covf <- fread(covfile)
  if(grepl(",", covs)){
    mycovs <- gsub("\\s+","",covs)
    mycovs <- strsplit(mycovs, ",")[[1]]
  } else{
    mycovs <- covs
  }
} else{
  print("No covariates files for input")
}

if(pcfile != "NULL"){
  pcvecs <- strsplit(pc_numbers, ",")[[1]]
  pcs <- fread(pcfile, select = c("FID", "IID", pcvecs))
} else{
  print("No PC files for input")
}

#################expression for models#################
if(!is.null(covfile) & !is.null(covs)){
  exp0 <- paste0(paste0(mycovs, collapse = " + "), paste0(" + ", pcvecs, collapse = "")) # base model with covariates only
  exp1 <- paste0("ZSCORE + ", paste0(mycovs, collapse = " + "), paste0(" + ", pcvecs, collapse = "")) # full model with PRS
} else{
  exp0 <- "1"
  exp1 <- paste0("ZSCORE")
}

select_cols <- c("FID", "IID", pheno)
phen_tmp <- phen[,..select_cols]
names(phen_tmp)[3] <- "Y"
phen_tmp <- phen_tmp[Y %in% c(0,1,2)]
full_ids <- phen_tmp[IID %in% ids$V2]

################get the accuracy metrics for each score file in validation cohort###########
vectorFiles <- strsplit(files, ",")[[1]]
scores1 <- c("#FID", "IID", "SCORE1_SUM")
scores2 <- c("FID", "IID", "SCORESUM")

listDf <- lapply(vectorFiles, function(fileName){
  if(grepl(".sscore", fileName)){
    dfFile <- fread(fileName,  stringsAsFactors = F)[,..scores1]
  } else if(grepl(".profile", fileName)){
    dfFile <- fread(fileName,  stringsAsFactors = F)[,..scores2]
  }
  names(dfFile) <- c("FID", "IID", fileName)
  return(dfFile)
})

dfMerged <- Reduce(function(...) merge(..., by = c("FID", "IID")), listDf)

res_wts <- data.table()
res_final <- data.table()

set.seed(2345)
for(Rep in 1:reps) {
  ids_1 <- full_ids[sample(nrow(full_ids), nrow(full_ids) * prop)] ###used as validation cohort
  ids_2 <- full_ids[!IID %in% ids_1$IID] ####used as testing cohort
  res <- data.table()
  for(prsfile in vectorFiles){
    #################reading input files#################
    prs_all <- fread(prsfile)
    fn <- tail(strsplit(prsfile, "/")[[1]], 1)
    prefix <- gsub(paste(c(".profile", ".sscore"), collapse = "|"), "",  fn) 
    
    prs <- prs_all[IID %in% ids_1$IID]
    
    prs[,PHENO := phen[prs, on = "IID"][,get(..pheno)]]
    
    if(max(prs[,PHENO], na.rm = T) == 2){
      prs[,PHENO := PHENO - 1 ]# change disease phenotype from 1/2 control case to 0/1
    }
    
    ##get SCORESUM based on plink version
    scores <- c("SCORESUM", "SCORE1_SUM")
    prs[,SCORESUM := get(grep(paste(scores, collapse = "|"), names(prs), value = T))]
    prs[,ZSCORE := (SCORESUM - mean(SCORESUM[PHENO == 0]))/sd(SCORESUM[PHENO==0])] # z-score of the profile score
    
    prs <- cbind(prs, covf[prs, on = "IID",][, mycovs, with = FALSE])
    prs <- cbind(prs, pcs[prs, on = "IID",][, ..pcvecs])
    prs <- na.omit(prs)
    
    
    Part <- "Validation"
    N <-  prs[PHENO %in% c(0,1), .N]
    
    P <- prs[PHENO == 1, .N] / N ##proportion of cases
    if(K == "NULL" | is.null(K)){
      K  <- P
    } else {
      K <- as.numeric(K)
    }
    
    tmp <- cal_NKr2_auc(prs)
    NKr2 <- tmp$NKr2
    NKr2_pval <- tmp$NKr2_pval
    
    # calculate liability scale using NKr2 
    h2l_NKr2 <- h2l_R2s(K, NKr2, P)

    res_part <- data.frame(Part, cohort, ldref, prefix, pheno, pop, N, K, P, 
                           NKr2, NKr2_pval,
                           h2l_NKr2, Rep)
    
    names(res_part) <- c("Part", "Cohort", "LDref", "prsFile", "Phenotype", "Pop", "N", "K", "P", 
                         "NKr2","NKr2_pval", 
                         "h2l_NKr2", "Rep")
    
    res <- rbind(res, res_part)
  }
  res_wts <- rbind(res_wts, res)
  
  ##########################merge_socreFiles_weighted##########################
  wts1 <- res[Part == "Validation", get(..wt)]

  if(grepl(".sscore", vectorFiles[1])){
    dfMerged_2 <- dfMerged
    dfMerged_2$SCORE1_SUM <- rowSums(as.matrix(dfMerged[,3:ncol(dfMerged)])  %*% diag(wts1))
    prs_wt <- dfMerged_2[,c("FID", "IID", "SCORE1_SUM")]
  } else{
    dfMerged_2$SCORESUM <- rowSums(as.matrix(dfMerged[,3:ncol(dfMerged)]) %*% diag(wts1))
    prs_wt <- dfMerged_2[,c("FID", "IID", "SCORESUM")]
  }
  
  ######################calculate PRS accuracy metrics based on weighted PRS in the test cohort####################
  res2 <- data.table()
  
  prs_wt2 <- prs_wt[IID %in% ids_2$IID]
  prs_wt2[,PHENO := phen[prs_wt2, on = "IID"][,get(..pheno)]]
  
  if(max(prs_wt2[,PHENO], na.rm = T) == 2){
    prs_wt2[,PHENO := PHENO - 1 ]# change disease phenotype from 1/2 control case to 0/1
  }
  
  ##get SCORESUM based on plink version
  scores <- c("SCORESUM", "SCORE1_SUM")
  prs_wt2[,SCORESUM := get(grep(paste(scores, collapse = "|"), names(prs_wt2), value = T))]
  prs_wt2[,ZSCORE := (SCORESUM - mean(SCORESUM[PHENO == 0]))/sd(SCORESUM[PHENO==0])] # z-score of the profile score
  
  prs_wt2 <- cbind(prs_wt2, covf[prs_wt2, on = "IID",][, mycovs, with = FALSE])
  prs_wt2 <- cbind(prs_wt2, pcs[prs_wt2, on = "IID",][, ..pcvecs])
  prs_wt2 <- na.omit(prs_wt2)
  
  
  Part2 <- "Test"
  N_wt <-  prs_wt2[PHENO %in% c(0,1), .N]
  
  P_wt <- prs_wt2[PHENO == 1, .N] / N_wt ##proportion of cases
  K  <- P_wt
  
  tmp <- cal_NKr2_auc(prs_wt2)
  NKr2 <- tmp$NKr2
  NKr2_pval <- tmp$NKr2_pval
  
  # calculate liability scale using NKr2 
  h2l_NKr2 <- h2l_R2s(K, NKr2, P_wt)
  
  results <- boot(prs_wt2, boot_function, R = 1000)
  
  NKr2_2.5 <- round(boot.ci(results, type ="perc", index = 1)[[4]][1,][4], 6)
  NKr2_97.5 <- round(boot.ci(results, type ="perc", index = 1)[[4]][1,][5], 6)
  h2l_NKr2_2.5 <- round(boot.ci(results, type ="perc", index = 2)[[4]][1,][4], 6)
  h2l_NKr2_97.5 <- round(boot.ci(results, type ="perc", index = 2)[[4]][1,][5], 6)
  
  res2 <- data.frame(Part2, cohort, ldref, prefix, pheno, pop, N_wt, K, P_wt, 
                     NKr2, NKr2_pval, NKr2_2.5, NKr2_97.5,
                     h2l_NKr2, h2l_NKr2_2.5, h2l_NKr2_97.5,
                     tmp[,3:ncol(tmp)], Rep)
  
  names(res2) <- c("Part", "Cohort", "LDref", "prs_wt2File", "Phenotype", "Pop", "N", "K", "P", 
                   "NKr2","NKr2_pval", "NKr2_2.5", "NKr2_97.5", 
                   "h2l_NKr2", "h2l_NKr2_2.5", "h2l_NKr2_97.5", 
                   "auc1", "auc1_2.5", "auc1_97.5", 
                   "auc2", "auc2_2.5", "auc2_97.5", "Rep")
  res_final <- rbind(res_final, res2)
}

fwrite(res_wts, file = out_weights, sep = "\t") ## the weighted accurracies across replicates
fwrite(res_final, file = out_test_metrics, sep = "\t") ## the final accurracies across replicates
