#!/usr/bin/env Rscript

###################################################################
####calculate PRS accuracy metrics for disease traits II       ####
####Ying Wang (yiwang@broadinstitute.org) in Aug-2021          ####
###################################################################

########load packages needed########
library(data.table)
library(optparse) #for parsing arguments

#########parsing argument options########
option_list <- list(
  make_option(c("--pop"), type = "character", default = NULL, help = "Target ancestry"),
  make_option(c("--pheno"), type = "character", default = NULL, help = "Phenotype name in the phenotype file"),
  make_option(c("--phenofile"), type = "character", default = NULL, help = "Full path and file name to phenotype files (including FID, IID, phenotypes etc.)"),
  make_option(c("--popfile"), type = "character", default = NULL, help = "Full path and file name to the file listing IDs for unrelated individuals in the target population (in the format of FID, IID as the first two columns)"),
  make_option(c("--prsfile"), type = "character", default = NULL, help = "Full path and file name to a *.profile generated by Plink1.* or *.sscore by Plink2.*, note using --sum to get the SCORESUM for Plink 1.* or cols=+scoresums to get SCORE1_SUM for Plink 2.* used in this script"),
  make_option(c("--covs"), type = "character", default = NULL, help = "Covariates included in the prediction model, separated by comma"),
  make_option(c("--pc_numbers"), type = "character", default = "PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10", help = "PCs included in the prediction model, separated by comma"),
  make_option(c("--covfile"), type = "character", default = NULL, help = "Full path and file name to the file including covariates (with headers including FID, IID and covariates)"),
  make_option(c("--pcfile"), type = "character", default = NULL, help = "Full path and file name to the file including PCs (e.g., headers including FID, IID, PC1, PC2, PC3...)"),
  make_option(c("--n_tiles"), type = "numeric", default = 10, help = "Number of tiles splitted, default is based on deciles"),
  make_option(c("--cohort_name"), type = "character", default = NULL, help = "Your specific Biobanks name"),
  make_option(c("--ldref"), type = "character", default = NULL, help = "The LD reference panel used (e.g., 1KG or UKB)"),
  make_option(c("--outf"), type = "character", default = NULL, help = "Full path and file name for the output file of the prs accuracy metrics")
)

opt = parse_args(OptionParser(option_list=option_list))

pop <- opt$pop
pheno <- opt$pheno
phenofile <- opt$phenofile
popfile <- opt$popfile
prsfile <- opt$prsfile
covfile <- opt$covfile
covs <- opt$covs
pcfile <- opt$pcfile
pc_numbers <- opt$pc_numbers
ntiles <- as.numeric(opt$n_tiles)
cohort <- opt$cohort_name
ldref <- opt$ldref
outf <- opt$outf

#################reading input files#################
if(prsfile != "NULL"){
  prs_all <- fread(prsfile)
  fn <- tail(strsplit(prsfile, "/")[[1]], 1)
  prefix <- gsub(paste(c(".profile", ".sscore"), collapse = "|"), "",  fn) 
} else {
  print("Error: No PRS score files for input!")
}

if(popfile != "NULL"){
  ids <- fread(popfile, header = F) ##read target population ids
  prs <- prs_all[IID %in% ids$V2,]
} else {
  prs <- prs_all
}

if(phenofile != "NULL"){
  phen <- fread(phenofile) ##including fields FID, IID, ...phenotypes...
  prs[,PHENO := phen[prs, on = "IID"][,get(..pheno)]]
  prs <- prs[PHENO %in% c(0, 1, 2)] ##remove PHENO as -9 or other NA
  
  if(max(prs[,PHENO], na.rm = T) == 2){
    prs[,PHENO := PHENO - 1 ]# change disease phenotype from 1/2 control case to 0/1
  }
} else{
  print("No phenotype files for input")
}

##get SCORESUM based on plink version
scores <- c("SCORESUM", "SCORE1_SUM")
prs[,SCORESUM := get(grep(paste(scores, collapse = "|"), names(prs), value = T))]
fits <- summary(glm(PHENO ~ SCORESUM, data = prs, family = binomial(logit))) ###check the effect direction 
prs[,SCORESUM := SCORESUM * sign(fits$coefficients[[2]])]
prs[,ZSCORE := (SCORESUM - mean(SCORESUM[PHENO == 0]))/sd(SCORESUM[PHENO==0])] # normalize SCORESUM in the controls

if(length(covs) > 0 & covfile != "NULL" & covs != "NULL" ){
  covf <- fread(covfile)
  if(grepl(",", covs)){
    mycovs <- gsub("\\s+","",covs)
    mycovs <- strsplit(mycovs, ",")[[1]]
  } else{
    mycovs <- covs
  }
  prs <- cbind(prs, covf[prs, on = "IID",][, mycovs, with = FALSE])
} else{
  print("No covariates files for input")
}

if(pcfile != "NULL") {
  pcvecs <- strsplit(pc_numbers, ",")[[1]]
  pcs <- fread(pcfile, select = c("FID", "IID", pcvecs))
  prs <- cbind(prs, pcs[prs, on = "IID",][, ..pcvecs])
} else {
  print("No PC files for input")
}

prs <- na.omit(prs)


## cut ZSCORE based on ntiles
prs$nt = cut(prs$ZSCORE, breaks=c(quantile(prs$ZSCORE, probs = seq(0, 1, by = 1/ntiles))), labels=1:ntiles, include.lowest=T)
prs[,nt2 := ifelse(nt != ntiles, 1, 2)]
prs$nt2 <- relevel(factor(prs$nt2), ref='1')
if(ntiles %% 2 == 0){
  mid_tiles <- c(ntiles/2, ntiles/2 + 1)
} else{
  mid_tiles <- c((ntiles + 1) / 2)
}
prs_sub <- prs[nt %in% c(ntiles, mid_tiles)]
prs_sub[,nt3 := ifelse(nt != ntiles, 1, 2)]
prs_sub$nt3 <- relevel(factor(prs_sub$nt3), ref='1')

#################expression for models#################
if(covfile != "NULL" & covs != "NULL" &  pcfile != "NULL"){
  exp <- paste0("nt + ", paste0(mycovs, collapse = " + "), paste0(" + ", pcvecs, collapse = "")) # full model with PRS
  exp2 <- paste0("nt2 + ", paste0(mycovs, collapse = " + "), paste0(" + ", pcvecs, collapse = "")) # full model with PRS
  exp3 <- paste0("nt3 + ", paste0(mycovs, collapse = " + "), paste0(" + ", pcvecs, collapse = "")) # full model with PRS
  exp4 <- paste0("nt4 + ", paste0(mycovs, collapse = " + "), paste0(" + ", pcvecs, collapse = "")) # full model with PRS
} else {
  exp <- paste0("nt")
  exp2 <- paste0("nt2")
  exp3 <- paste0("nt3")
  exp4 <- paste0("nt4")
}

glm_nt <- glm(as.formula(paste("PHENO ~ ", exp)), data = prs, family = binomial(logit))
glm_nt2 <- glm(as.formula(paste("PHENO ~ ", exp2)), data = prs, family = binomial(logit))
glm_nt3 <- glm(as.formula(paste("PHENO ~ ", exp3)), data = prs_sub, family = binomial(logit))


#Odds ratio for being a case compared to control in each tile when using first tile as referenced group
ORs <- exp(glm_nt$coefficients)
ORs_2.5 <- exp(glm_nt$coefficients - 1.96 * summary(glm_nt)$coefficients[,2])
ORs_97.5 <- exp(glm_nt$coefficients + 1.96 * summary(glm_nt)$coefficients[,2])
ORs_pvals <- summary(glm_nt)$coefficients[,4]

##OR for Top tile VS the remaining individuals
ORs_topVSother <- exp(glm_nt2$coefficients)
ORs_topVSother_2.5 <- exp(glm_nt2$coefficients - 1.96 * summary(glm_nt2)$coefficients[,2])
ORs_topVSother_97.5 <- exp(glm_nt2$coefficients + 1.96 * summary(glm_nt2)$coefficients[,2])
ORs_topVSother_pvals <- summary(glm_nt2)$coefficients[,4]

##OR for Top tile VS the middle
ORs_topVSmid <- exp(glm_nt3$coefficients)
ORs_topVSmid_2.5 <- exp(glm_nt3$coefficients - 1.96 * summary(glm_nt3)$coefficients[,2])
ORs_topVSmid_97.5 <- exp(glm_nt3$coefficients + 1.96 * summary(glm_nt3)$coefficients[,2])
ORs_topVSmid_pvals <- summary(glm_nt3)$coefficients[,4]

outs <- data.table()
ref_group <- "first_tile"
for(i in 1:ntiles){
  mean_control <- prs[PHENO == 0 & nt == i, mean(ZSCORE)]
  mean_case <- prs[PHENO == 1 & nt == i, mean(ZSCORE)]
  median_control <- prs[PHENO == 0 & nt == i, median(ZSCORE)]
  median_case <- prs[PHENO == 1 & nt == i, median(ZSCORE)]
  N_control <- prs[PHENO == 0 & nt == i, .N]
  N_case <- prs[PHENO == 1 & nt == i, .N]
  
  mean_control_other <- prs[PHENO == 0 & nt2 == 1, mean(ZSCORE)]
  mean_case_other <- prs[PHENO == 1 & nt2 == 1, mean(ZSCORE)]
  median_control_other <- prs[PHENO == 0 & nt2 == 1, median(ZSCORE)]
  median_case_other <- prs[PHENO == 1 & nt2 == 1, median(ZSCORE)]
  N_control_other <- prs[PHENO == 0 & nt2 == 1, .N]
  N_case_other <- prs[PHENO == 1 & nt2 == 1, .N]
  
  mean_control_mid <- prs_sub[PHENO == 0 & nt3 == 1, mean(ZSCORE)]
  mean_case_mid <- prs_sub[PHENO == 1 & nt3 == 1, mean(ZSCORE)]
  median_control_mid <- prs_sub[PHENO == 0 & nt3 == 1, median(ZSCORE)]
  median_case_mid <- prs_sub[PHENO == 1 & nt3 == 1, median(ZSCORE)]
  N_control_mid <- prs_sub[PHENO == 0 & nt3 == 1, .N]
  N_case_mid <- prs_sub[PHENO == 1 & nt3 == 1, .N]

  if(i == 1){
    outs_tmp <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, i, N_control, N_case, 1, 1, 1, 0, mean_control, mean_case, median_control, median_case)
  } else if(i == ntiles){
    outs_tmp1 <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, i, N_control, N_case, ORs[i], ORs_2.5[i], ORs_97.5[i], ORs_pvals[i], mean_control, mean_case, median_control, median_case)
    outs_tmp2 <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, "topVSother", N_control_other, N_case_other, ORs_topVSother[2], ORs_topVSother_2.5[2], ORs_topVSother_97.5[2], ORs_topVSother_pvals[2], mean_control_other, mean_case_other, median_control_other, median_case_other)
    outs_tmp3 <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, "topVSmid", N_control_mid, N_case_mid, ORs_topVSmid[2], ORs_topVSmid_2.5[2], ORs_topVSmid_97.5[2], ORs_topVSmid_pvals[2], mean_control_mid, mean_case_mid, median_control_mid, median_case_mid)
    names(outs_tmp2) <- names(outs_tmp1)
    names(outs_tmp3) <- names(outs_tmp1)
    
    outs_tmp <- rbind(outs_tmp1, outs_tmp2, outs_tmp3)
  } else {
    outs_tmp <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, i, N_control, N_case, ORs[i], ORs_2.5[i], ORs_97.5[i], ORs_pvals[i], mean_control, mean_case, median_control, median_case)
  }
  outs <- rbind(outs, outs_tmp)
}


#################ORs using the middle tiles as referenced group#################
prsII <- prs
prsII[,nt4 := ifelse(nt %in% mid_tiles, -1, nt)]
prsII$nt4 <- factor(prsII$nt4)
prsII$nt4 <- relevel(prsII$nt4, ref='-1')

glm_ntII <- glm(as.formula(paste("PHENO ~ ", exp4)), data = prsII, family = binomial(logit))


#Odds ratio for being a case compared to control in each tile
ORsII <- exp(glm_ntII$coefficients)
ORsII_2.5 <- exp(glm_ntII$coefficients - 1.96 * summary(glm_ntII)$coefficients[,2])
ORsII_97.5 <- exp(glm_ntII$coefficients + 1.96 * summary(glm_ntII)$coefficients[,2])
ORsII_pvals <- summary(glm_ntII)$coefficients[,4]

ref_group <- "mid_tile"
for(i in 1:ntiles){
  mean_control <- prs[PHENO == 0 & nt == i, mean(ZSCORE)]
  mean_case <- prs[PHENO == 1 & nt == i, mean(ZSCORE)]
  median_control <- prs[PHENO == 0 & nt == i, median(ZSCORE)]
  median_case <- prs[PHENO == 1 & nt == i, median(ZSCORE)]
  N_control <- prs[PHENO == 0 & nt == i, .N]
  N_case <- prs[PHENO == 1 & nt == i, .N]
  
  if (i < min(mid_tiles)) {
    outs_tmp <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, i, N_control, N_case, ORsII[i + 1], ORsII_2.5[i + 1], ORsII_97.5[i + 1], ORsII_pvals[i + 1], mean_control, mean_case, median_control, median_case)
  } else if (i %in% mid_tiles){
    outs_tmp <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, i, N_control, N_case, 1, 1, 1, 0, mean_control, mean_case, median_control, median_case)
  } else if(length(mid_tiles) > 1 & i > max(mid_tiles)){
    outs_tmp <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, i, N_control, N_case, ORsII[i - 1], ORsII_2.5[i - 1], ORsII_97.5[i - 1], ORsII_pvals[i - 1], mean_control, mean_case, median_control, median_case)
  } else {
    outs_tmp <- data.table(ref_group, cohort, ldref, prefix, pheno, pop, i, N_control, N_case, ORsII[i], ORsII_2.5[i], ORsII_97.5[i], ORsII_pvals[i], mean_control, mean_case, median_control, median_case)
  }
  outs <- rbind(outs, outs_tmp)
}

names(outs) <- c("Referenced_group", "Cohort", "LDref", "prsFile", "Phenotype", "Pop", "Nt","N_control", "N_case",  "OR", "OR_2.5", "OR_97.5","OR_pval", "Mean_PGS_controls", "Mean_PGS_cases", "Median_PGS_controls", "Median_PGS_cases")

fwrite(outs, outf, sep = "\t")
