#!/usr/bin/env Rscript

###################################################################
####calculate PRS accuracy metrics for disease traits II       ####
####Ying Wang (yiwang@broadinstitute.org) in Aug-2021          ####
###################################################################

########load packages needed########
library(data.table)
library(optparse) #for parsing arguments

#########parsing argument options########
option_list <- list(
  make_option(c("--pop"), type = "character", default = NULL, help = "Target ancestry"),
  make_option(c("--pheno"), type = "character", default = NULL, help = "Phenotype name in the phenotype file"),
  make_option(c("--phenofile"), type = "character", default = NULL, help = "Full path and file name to phenotype files (including FID, IID, phenotypes etc.)"),
  make_option(c("--popfile"), type = "character", default = NULL, help = "Full path and file name to the file listing IDs for unrelated individuals in the target population (in the format of FID, IID as the first two columns)"),
  make_option(c("--prsfile"), type = "character", default = NULL, help = "Full path and file name to a *.profile generated by Plink1.* or *.sscore by Plink2.*, note using --sum to get the SCORESUM for Plink 1.* or cols=+scoresums to get SCORE1_SUM for Plink 2.* used in this script"),
  make_option(c("--covs"), type = "character", default = NULL, help = "Covariates included in the prediction model, separated by comma"),
  make_option(c("--pc_numbers"), type = "character", default = "PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10", help = "PCs included in the prediction model, separated by comma"),
  make_option(c("--covfile"), type = "character", default = NULL, help = "Full path and file name to the file including covariates (with headers including FID, IID and covariates)"),
  make_option(c("--pcfile"), type = "character", default = NULL, help = "Full path and file name to the file including PCs (e.g., headers including FID, IID, PC1, PC2, PC3...)"),
  make_option(c("--n_tiles"), type = "numeric", default = 10, help = "Number of tiles splitted, default is based on deciles"),
  make_option(c("--cohort_name"), type = "character", default = NULL, help = "Your specific Biobanks name"),
  make_option(c("--ldref"), type = "character", default = NULL, help = "The LD reference panel used (e.g., 1KG or UKB)"),
  make_option(c("--outf"), type = "character", default = NULL, help = "Full path and file name for the output file of the prs accuracy metrics")
)

opt = parse_args(OptionParser(option_list=option_list))

pop <- opt$pop
pheno <- opt$pheno
phenofile <- opt$phenofile
popfile <- opt$popfile
prsfile <- opt$prsfile
covfile <- opt$covfile
covs <- opt$covs
pcfile <- opt$pcfile
pc_numbers <- opt$pc_numbers
ntiles <- as.numeric(opt$n_tiles)
cohort <- opt$cohort_name
ldref <- opt$ldref
outf <- opt$outf

#################reading input files#################
if(prsfile != "NULL"){
  prs_all <- fread(prsfile)
  fn <- tail(strsplit(prsfile, "/")[[1]], 1)
  prefix <- gsub(paste(c(".profile", ".sscore"), collapse = "|"), "",  fn) 
} else {
  print("Error: No PRS score files for input!")
}

if(popfile != "NULL"){
  ids <- fread(popfile, header = F) ##read target population ids
  prs <- prs_all[IID %in% ids$V2,]
} else {
  prs <- prs_all
}

if(phenofile != "NULL"){
  phen <- fread(phenofile) ##including fields FID, IID, ...phenotypes...
  prs[,PHENO := phen[prs, on = "IID"][,get(..pheno)]]
  prs <- prs[PHENO %in% c(0, 1, 2)] ##remove PHENO as -9 or other NA
  
  if(max(prs[,PHENO], na.rm = T) == 2){
    prs[,PHENO := PHENO - 1 ]# change disease phenotype from 1/2 control case to 0/1
  }
} else{
  print("No phenotype files for input")
}

##get SCORESUM based on plink version
scores <- c("SCORESUM", "SCORE1_SUM")
prs[,SCORESUM := get(grep(paste(scores, collapse = "|"), names(prs), value = T))]
fits <- summary(glm(PHENO ~ SCORESUM, data = prs, family = binomial(logit))) ###check the effect direction 
prs[,SCORESUM := SCORESUM * sign(fits$coefficients[[2]])]
prs[,ZSCORE := (SCORESUM - mean(SCORESUM[PHENO == 0]))/sd(SCORESUM[PHENO==0])] # normalize SCORESUM in the controls

if(length(covs) > 0 & covfile != "NULL" & covs != "NULL" ){
  covf <- fread(covfile)
  if(grepl(",", covs)){
    mycovs <- gsub("\\s+","",covs)
    mycovs <- strsplit(mycovs, ",")[[1]]
  } else{
    mycovs <- covs
  }
  prs <- cbind(prs, covf[prs, on = "IID",][, mycovs, with = FALSE])
} else{
  print("No covariates files for input")
}

if(pcfile != "NULL") {
  pcvecs <- strsplit(pc_numbers, ",")[[1]]
  pcs <- fread(pcfile, select = c("FID", "IID", pcvecs))
  prs <- cbind(prs, pcs[prs, on = "IID",][, ..pcvecs])
} else {
  print("No PC files for input")
}

prs <- na.omit(prs)


#################expression for models#################
if(covfile != "NULL" & covs != "NULL" &  pcfile != "NULL"){
  exp <- paste0("nt + ", paste0(mycovs, collapse = " + "), paste0(" + ", pcvecs, collapse = "")) # full model with PRS
} else {
  exp <- paste0("nt")
}

## cut ZSCORE based on ntiles
prs$nt = cut(prs$ZSCORE, breaks=c(quantile(prs$ZSCORE, probs = seq(0, 1, by = 1/ntiles))), labels=1:ntiles, include.lowest=T)

glm_nt <- glm(as.formula(paste("PHENO ~ ", exp)), data = prs, family = binomial(logit))


#Odds ratio for being a case compared to control in each decile
ORs <- exp(glm_nt$coefficients)
ORs_2.5 <- exp(glm_nt$coefficients - 1.96 * summary(glm_nt)$coefficients[,2])
ORs_97.5 <- exp(glm_nt$coefficients + 1.96 * summary(glm_nt)$coefficients[,2])

outs <- data.table()
for(i in 1:ntiles){
  mean_control <- prs[PHENO == 0 & nt == i, mean(ZSCORE)]
  mean_case <- prs[PHENO == 1 & nt == i, mean(ZSCORE)]
  median_control <- prs[PHENO == 0 & nt == i, median(ZSCORE)]
  median_case <- prs[PHENO == 1 & nt == i, median(ZSCORE)]
  N_control <- prs[PHENO == 0 & nt == i, .N]
  N_case <- prs[PHENO == 1 & nt == i, .N]
  
  outs_tmp <- data.table(cohort, ldref, prefix, pheno, pop, i, N_control, N_case, ORs[i], ORs_2.5[i], ORs_97.5[i], mean_control, mean_case, median_control, median_case)
  outs <- rbind(outs, outs_tmp)
}
names(outs) <- c("Cohort", "LDref", "prsFile", "Phenotype", "Pop", "Nt","N_control", "N_case",  "OR", "OR_2.5", "OR_97.5", "Mean_PGS_controls", "Mean_PGS_cases", "Median_PGS_controls", "Median_PGS_cases")

fwrite(outs, outf, sep = "\t")
