#!/usr/bin/env Rscript

###################################################################
####Merge PRS score file across chromosomes                    ####
####Ying Wang (yiwang@broadinstitute.org) in June-2021         ####
###################################################################

library(data.table)
library(optparse) #for parsing arguments

#########parsing argument options########
option_list <- list(
  make_option(c("-w", "--wkdir"), type = "character", default = NULL, help = "Full path to the directory with score files .profile or .sscore generated by plink"),
  make_option(c("-f", "--file_pattern"), type = "character", default = NULL, help = "a regex pattern for score files (*profile or *sscore generated by Plink) with 22 chromosomes"),
  make_option(c("-o", "--out_file"), type = "character", default = NULL, help = "Full path and file name for the combined score file.")
)

opt = parse_args(OptionParser(option_list=option_list))

wkdir <- opt$wkdir
file_pattern <- opt$file_pattern
outf <- opt$out_file

vectorFiles <- list.files(path = wkdir, pattern = glob2rx(pattern = file_pattern))

scores1 <- c("#FID", "IID", "SCORE1_SUM")
scores2 <- c("FID", "IID", "SCORESUM")

if(length(vectorFiles) ==  22){
  listDf <- lapply(vectorFiles, function(fileName){
    if(grepl(".sscore", fileName)){
      dfFile <- fread(paste0(wkdir, "/", fileName),  stringsAsFactors = F)[,..scores1]
    } else if(grepl(".profile", fileName)){
      dfFile <- fread(paste0(wkdir, "/", fileName),  stringsAsFactors = F)[,..scores2]
    }
    
    names(dfFile) <- c("FID", "IID", fileName)
    return(dfFile)
  })
  
  # merge the data frames on the column Col1
  dfMerged <- Reduce(function(...) merge(..., by = c("FID", "IID")), listDf)
  
  if(grepl(".sscore", file_pattern)){
    dfMerged[,SCORE1_SUM := rowSums(as.matrix(dfMerged[,3:ncol(dfMerged)]))]
    prs <- dfMerged[,c("FID", "IID", "SCORE1_SUM")]
  } else{
    dfMerged[,SCORESUM := rowSums(as.matrix(dfMerged[,3:ncol(dfMerged)]))]
    prs <- dfMerged[,c("FID", "IID", "SCORESUM")]
  }
  
  fwrite(prs, outf, sep = "\t")
} else {
  print("There are no 22 score files.")
}
