#!/usr/bin/env Rscript

###################################################################
####Merge PRS score file across chromosomes                    ####
####Ying Wang (yiwang@broadinstitute.org) in June-2021         ####
###################################################################

library(data.table)
library(optparse) #for parsing arguments

#########parsing argument options########
option_list <- list(
  make_option(c("-w", "--wkdir"), type = "character", default = NULL, help = "Full path to the directory with score files generated by plink"),
  make_option(c("-f", "--file_pattern"), type = "character", default = NULL, help = "a regex pattern for score files with multiple chromosomes"),
  make_option(c("-o", "--outdir"), type = "character", default = NULL, help = "Output file for combined PRS")
)

opt = parse_args(OptionParser(option_list=option_list))

wkdir <- opt$wkdir
file_pattern <- opt$file_pattern
outf <- opt$outdir

vectorFiles <- list.files(path = wkdir, pattern = glob2rx(pattern = file_pattern))

listDf <- lapply(vectorFiles, function(fileName){
  dfFile <- fread(paste0(wkdir, "/", fileName),  stringsAsFactors = F)[,c(1,2,3, 6)]
  names(dfFile)[4] <- fileName
  return(dfFile)
})

# merge the data frames on the column Col1
dfMerged <- Reduce(function(...) merge(..., by = c("FID", "IID", "PHENO")), listDf)
#print(dfMerged)
dfMerged[,SCORESUM := rowSums(as.matrix(dfMerged[,4:ncol(dfMerged)]))]

prs <- dfMerged[,c("FID", "IID","PHENO", "SCORESUM")]

fwrite(prs, outf, sep = "\t")

