PATH_TO_REFERENCE=""
VALIDATION_BIM_PREFIX=""
GWAS_SAMPLE_SIZE=
SUM_STATS_FILE=""
OUTPUT_DIR=""
N_THREADS=""
PATH_TO_PRSCS_DIR=""

chrom=${TASK_ID}

export MKL_NUM_THREADS=$N_THREADS
export NUMEXPR_NUM_THREADS=$N_THREADS
export OMP_NUM_THREADS=$N_THREADS

python3 $PATH_TO_PRSCS_DIR/PRScs.py --ref_dir=$PATH_TO_REFERENCE \
--bim_prefix=$VALIDATION_BIM_PREFIX --chrom=$chrom \
--sst_file=$SUM_STATS_FILE --n_gwas=$GWAS_SAMPLE_SIZE \
--out_dir=$OUTPUT_DIR 

